"""Initial schema

Revision ID: d0c2a0d5c427
Revises: 
Create Date: 2026-07-08 21:30:20.252425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0c2a0d5c427'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('artist', sa.String(), nullable=True),
    sa.Column('album', sa.String(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('original_genre', sa.String(), nullable=True),
    sa.Column('cover_art', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_songs_hash'), 'songs', ['hash'], unique=True)
    op.create_index(op.f('ix_songs_path'), 'songs', ['path'], unique=True)
    op.create_table('audio_features',
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('bpm', sa.Float(), nullable=True),
    sa.Column('chroma', sa.LargeBinary(), nullable=True),
    sa.Column('mfcc', sa.LargeBinary(), nullable=True),
    sa.Column('spectral_centroid', sa.LargeBinary(), nullable=True),
    sa.Column('spectral_contrast', sa.LargeBinary(), nullable=True),
    sa.Column('rms', sa.LargeBinary(), nullable=True),
    sa.Column('zero_crossing_rate', sa.LargeBinary(), nullable=True),
    sa.Column('key_estimation', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('song_id')
    )
    op.create_table('embeddings',
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('vector', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('song_id')
    )
    op.create_table('listening_history',
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('play_count', sa.Integer(), nullable=False),
    sa.Column('skips', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Boolean(), nullable=False),
    sa.Column('last_played', sa.DateTime(), nullable=True),
    sa.Column('play_duration', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('song_id')
    )
    op.create_table('musicbrainz_metadata',
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('canonical_artist', sa.String(), nullable=True),
    sa.Column('canonical_album', sa.String(), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('canonical_genre', sa.String(), nullable=True),
    sa.Column('musicbrainz_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('song_id')
    )
    op.create_table('semantic_tags',
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('moods', sa.String(), nullable=True),
    sa.Column('activities', sa.String(), nullable=True),
    sa.Column('themes', sa.String(), nullable=True),
    sa.Column('descriptors', sa.String(), nullable=True),
    sa.Column('energy', sa.String(), nullable=True),
    sa.Column('vocal_style', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('song_id')
    )
    op.create_table('technical_metadata',
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('codec', sa.String(), nullable=True),
    sa.Column('bitrate', sa.Integer(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('channels', sa.Integer(), nullable=True),
    sa.Column('bit_depth', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('song_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('technical_metadata')
    op.drop_table('semantic_tags')
    op.drop_table('musicbrainz_metadata')
    op.drop_table('listening_history')
    op.drop_table('embeddings')
    op.drop_table('audio_features')
    op.drop_index(op.f('ix_songs_path'), table_name='songs')
    op.drop_index(op.f('ix_songs_hash'), table_name='songs')
    op.drop_table('songs')
    # ### end Alembic commands ###
