name: Deploy Testing

on:
  push:
    branches:
      - Testing

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Update repository
        run: |
          cd /home/pyro/apps/Verse-test

          git fetch origin
          git checkout Testing
          git reset --hard origin/Testing

      - name: Restart Verse
        run: |
          sudo systemctl restart verse-test
          systemctl status verse-test --no-pager
